### ISSUE TITLE
module 'paho.mqtt.client' has no attribute 'CallbackAPIVersion'

### ISSUE THREAD

**Issue by MarioWalln** [LundSoftwares/venus-os_dbus-mqtt-tank-levels-x3#1]
I installed on venusos 3.55 on a raspberry.
This is the error that i am getting:

```
2025-06-16 13:21:26.322609500 *** starting dbus-mqtt-tank-levels ***
2025-06-16 13:21:27.813672500 Traceback (most recent call last):
2025-06-16 13:21:27.813679500   File "/data/etc/dbus-mqtt-tank-levels/dbus-mqtt-tank-levels.py", line 630, in <module>
2025-06-16 13:21:27.813685500     main()
2025-06-16 13:21:27.813686500   File "/data/etc/dbus-mqtt-tank-levels/dbus-mqtt-tank-levels.py", line 517, in main
2025-06-16 13:21:27.813691500     client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION2,"MqttLevel_" + str(config["MQTT"]["device_instance"]))
2025-06-16 13:21:27.813697500 AttributeError: module 'paho.mqtt.client' has no attribute 'CallbackAPIVersion'
```

What can i do to make it run?

Mario

**Comment by MarioWalln** [comment]
seems to work with the version prior 3.5.2025

**Comment by LundSoftwares** [comment]
Correct, the latest submitted version of dbus-mqtt-tank-levels.py is made to work with VenusOS 3.60+
For 3.55, use the previous version, submitted on 2024-07-15: https://github.com/LundSoftwares/venus-os_dbus-mqtt-tank-levels-x3/tree/e8264034620c82efa7fc495fecb984a6154b089a/dbus-mqtt-tank-levels
